[package]
name = "ncgopher"
version = "0.1.4"
authors = ["Jan Schreiber <jan@mecinus.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "An ncurses gopher and gemini client for the modern internet"
documentation = "https://github.com/jansc/ncgopher/blob/master/README.org"
readme = "README.org"
homepage = "https://github.com/jansc/ncgopher"
repository = "https://github.com/jansc/ncgopher"
keywords = ["cli", "gopher", "client"]
categories = ["command-line-utilities", "network-programming"]
exclude = ["screenshots/**"]

[badges.travis-ci]
repository = "jansc/ncgopher"

[features]
tls = ["native-tls"]
default = ["tls"]

[dependencies]
unicode-width = "0.1.7"
url = "2.1.1"
chrono = "0.4.11"
lazy_static = "1.4.0"
clap = "2.33.0"
log = "0.4.8"
dirs = "2.0.2"
config = "0.10.1"
serde_derive = "1.0.106"
serde = { version = "1.0.106", features = ["derive"] }
toml = "0.5.6"
rusqlite = { version = "0.23.1", features = ["url", "chrono"] }
regex = "1.3.7"
textwrap = "0.11.0"

native-tls = { version = "0.2.4", optional = true }
x509-parser = "0.8.0-beta1"
pancurses = "0.16.1"
base64 = "0.12.1"

[dependencies.cursive]
version = "0.15.0"
#git = "https://github.com/gyscos/cursive"
default-features = false
features = ["pancurses-backend", "toml"]
