[package]
name = "ncgopher"
version = "0.1.5"
authors = ["Jan Schreiber <jan@mecinus.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "An ncurses gopher and gemini client for the modern internet"
documentation = "https://github.com/jansc/ncgopher/blob/master/README.org"
readme = "README.md"
homepage = "https://github.com/jansc/ncgopher"
repository = "https://github.com/jansc/ncgopher"
keywords = ["cli", "gopher", "gemini", "client"]
categories = ["command-line-utilities", "network-programming"]
exclude = ["screenshots/**"]

[badges.travis-ci]
repository = "jansc/ncgopher"

[dependencies]
unicode-width = "0.1.8"
url = "2.2"
chrono = "0.4.19"
lazy_static = "1.4.0"
clap = "2.33.3"
log = { version = "0.4.13", features = ["std"] }
dirs = "3.0.1"
config = "0.10.1"
serde_derive = "1.0"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9.2"
toml = "0.5.8"
rusqlite = { version = "0.24.2", features = ["url", "chrono"] }
gemtext = "0.2.1"
native-tls = "0.2.7"
x509-parser = "0.9.0"
pancurses = "0.16.1"
base64 = "0.13"
percent-encoding = "2.1"
idna = "0.2"
cursive = { version = "0.15", default-features = false, features = ["pancurses-backend", "toml"] }
