[package]
name = "ncgopher"
version = "0.1.3"
authors = ["Jan Schreiber <jan@mecinus.com>"]
edition = "2018"
license = "BSD-2-Clause"
description = "An ncurses gopher client for the modern internet"
documentation = "https://github.com/jansc/ncgopher/blob/master/README.org"
readme = "README.org"
homepage = "https://github.com/jansc/ncgopher"
repository = "https://github.com/jansc/ncgopher"
keywords = ["cli", "gopher", "client"]
categories = ["command-line-utilities", "network-programming"]
exclude = ["screenshots/**"]

[badges.travis-ci]
repository = "jansc/ncgopher"

[features]
tls = ["native-tls"]
default = ["tls"]

[dependencies]
unicode-width = "^0.1.5"
url = "^2.1.0"
chrono = "^0.4.9"
lazy_static = "^1.4.0"
clap = "^2.33.0"
log = "^0.4"
dirs = "^2.0.2"
config = "^0.9"
serde_derive = "^1.0.8"
serde = {version = "^1.0.8", features = ["derive"]}
toml = "0.5.6"
rusqlite = "0.16.0"

native-tls = { version = "0.2", optional = true }
pancurses = "0.16.1"

[dependencies.cursive]
version = "0.14"
#git = "https://github.com/gyscos/cursive"
default-features = false
features = ["pancurses-backend", "toml"]
